# Generated by Django 6.0.3 on 2026-03-21 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_financialaccount_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialaccount',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.transactioncategory'),
            preserve_default=False,
        ),
    ]
