# Generated by Django 6.0.3 on 2026-03-21 21:51

import FinanceTracker.common.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_target_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wants_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, FinanceTracker.common.mixins.BaseMixin),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
